export function getCitySeoParagraphs(displayCity: string, state: string, total: number): string[] {
  return [
    `Are you looking for the most reliable and affordable car hire in ${displayCity}, ${state}? Welcome to Hire Car, Australia’s premier vehicle rental marketplace that connects you directly with verified, local rental operators. Whether you are a local resident needing a temporary replacement vehicle, a business traveler requiring professional corporate transport, or a tourist eager to explore ${displayCity} and its breathtaking surrounding regions, our platform offers an extensive and diverse fleet to meet your specific travel requirements.`,

    `When you choose to rent a vehicle through our platform, you are choosing unparalleled transparency, security, and exceptional value. We understand that finding dependable car hire in ${displayCity} can sometimes be a daunting task, which is why we have simplified the entire process from start to finish. Every single vendor on our platform undergoes a rigorous verification process. We mandate strict ABN (Australian Business Number) validation and conduct comprehensive background approvals before any operator is allowed to list their vehicles. This stringent approach means you can browse, inquire, and book with absolute confidence, knowing you are dealing exclusively with legitimate, professional Australian rental companies.`,

    `One of the biggest advantages of using Hire Car in ${displayCity} is our steadfast commitment to a zero-booking-fee model. Unlike traditional online travel agencies or international brokers that often add hidden margins and excessive commission fees to your final bill, we connect you directly with the fleet owners. You communicate with the local operator directly to arrange your preferred travel dates, negotiate transparent pricing, and coordinate a convenient pickup and drop-off location within ${displayCity}. By completely cutting out the middleman, you secure the most competitive daily rates while directly supporting local Australian businesses.`,

    `Our marketplace is meticulously designed for ultimate flexibility and convenience. We boast a wide-ranging selection of vehicles tailored to navigate the unique driving conditions of ${displayCity} and the broader ${state} region. From compact hatchbacks and highly fuel-efficient sedans ideal for navigating busy city streets and tight urban parking spaces, to robust SUVs and 4WDs perfect for expansive family road trips and rugged outback adventures. We also comprehensively cater to group travel and commercial logistics with spacious people movers, versatile utes, and large-capacity moving trucks. You can effortlessly filter our active listings by vehicle category, fuel type, transmission, and daily price to pinpoint the exact vehicle that aligns perfectly with your itinerary and budget.`,

    `Experience the true freedom of the open road in ${displayCity} without the usual rental hassle. Start your journey today by browsing our verified listings ${total > 0 ? `featuring ${total} available vehicles ` : ''}above. Connect directly with trusted local experts, secure the best possible rate with no hidden fees, and discover why we are rapidly becoming the go-to destination for car hire across Australia.`
  ];
}
